services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    # command: bash -c "alembic upgrade head && uvicorn app.main:app"
    command: bash -c "uvicorn app.main:app --reload --host=0.0.0.0"
    restart: always
    volumes:
      - ../app:/app/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file:
      - ../.env

volumes:
  db_data:
