version: '3'
services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT

  backend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_backend"
    # command: bash -c "alembic upgrade head && uvicorn app.main:app"
    command: bash -c "uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./.env

  frontend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_frontend"
    ports:
      - 3000:3000

volumes:
  db_data:
