version: '3'
services:

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - $DB_PORT

  backend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_backend"
    # command: bash -c "alembic upgrade head && uvicorn app.main:app"
    command: bash -c "uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      - db
    expose:
      - 8000
    env_file:
      - ./.env

  frontend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_frontend"
    expose:
      - 3000

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:
